name: Build and Push Docker Image (Docker Hub Only)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Docker Hub'a giriş yap
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker imajını build et ve etiketle
        run: |
          docker build -t dikeckaan/pi5-fan-control-web:latest .

      - name: Docker Hub’a push et
        run: |
          docker push dikeckaan/pi5-fan-control-web:latest

      - name: Docker Hub README.md'yi imaj açıklaması olarak güncelle
        env:
          DOCKERHUB_REPO: dikeckaan/pi5-fan-control-web
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          curl -s -X PATCH https://hub.docker.com/v2/repositories/${DOCKERHUB_REPO}/ \
            -H "Content-Type: application/json" \
            -H "Authorization: JWT $(curl -s -X POST https://hub.docker.com/v2/users/login/ \
              -H "Content-Type: application/json" \
              -d "{\"username\": \"${DOCKERHUB_USERNAME}\", \"password\": \"${DOCKERHUB_TOKEN}\"}" | jq -r .token)" \
            -d "$(jq -n --arg full_desc "$(cat README.md)" '{"full_description": $full_desc}')"
