name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Docker Hub'a giriş yap
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GHCR'a giriş yap
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker imajını build et
        run: |
          docker build -t dikeckaan/pi5-fan-control-web:latest .
          docker tag dikeckaan/pi5-fan-control-web:latest ghcr.io/${{ github.repository_owner }}/pi5-fan-control-web:latest

      - name: Docker Hub’a push et
        run: |
          docker push dikeckaan/pi5-fan-control-web:latest

      - name: GHCR’a push et
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/pi5-fan-control-web:latest
